### ISSUE TITLE
Add a link to this tutorial to Helm's `related.md` page?

### ISSUE THREAD

**Issue by technosophos** [muffin87/helm-tutorial#3]
You're welcome to add a link to this tutorial to the official Helm docs here:

https://github.com/helm/helm/blob/master/docs/related.md

Thanks for the tutorial! It looks great!

**Comment by muffin87** [comment]
@technosophos wow that's cool! I will create a pull request ;)

**Comment by muffin87** [comment]
This was merged. Please see helm/helm#4466.
@technosophos thanks!!
